services:
  keras-api:
    build: .
    container_name: keras-api
    ports:
      - "8080:8080"
    depends_on:
      - keras-grpc

  keras-grpc:
    image: keras-grpc:v1
    container_name: keras-grpc